package:
  name: hello_world
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ../

build:
  skip: True # [py==38 and np==115]
  number: {{ GIT_DESCRIBE_NUMBER }}

  preserve_egg_dir: False
  
  noarch: python

  # entry_points:
  #   - helloworld = hello_world.hello_world:main

  missing_dso_whitelist:
    - /lib64/libc.so.6            # [linux]
    - /lib64/libm.so.6            # [linux]
    - /lib64/libpthread.so.0      # [linux]
    - /lib64/ld-linux-x86-64.so.2 # [linux]
    - C:\Windows\System32\ADVAPI32.dll # [win]
    - C:\Windows\System32\KERNEL32.dll # [win]
    - C:\Windows\System32\msvcrt.dll   # [win]
    - C:\Windows\System32\SHELL32.dll  # [win]


test:
  source_files:
    - ./test

  commands:
    - pip install -U setuptools
    - python -c "import os, glob; print ('TESTING IN THIS DIRECTORY' , os.getcwd()); print ([el for el in glob.glob('*')])"
    - python -m unittest discover test -v
  
requirements:
  
  build:
    - python 
    - openmp                # [osx]
    - cmake
    - numpy {{ numpy }}
    - setuptools

  run:
    - python
    - numpy
    - natsort
    - docopt
    - matplotlib
    - openmp                # [osx]
    - qdarkstyle

about:
  summary: 'Hello World'
