name: docs
channels:
  - conda-forge
  - intel
  - ccpi
  - defaults
dependencies:
  - python=3.7
  - numpy=1.18
  - scipy
  - matplotlib
  - h5py
  - pillow
  - libgcc-ng
  - dxchange
  - olefile
  - pywavelets
  - python-wget
  - scikit-image
  - scipy
  - packaging
  - tomophantom
  - numba
  - ipp
  - ipp-devel
  - ipp-include
  - tigre
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme
  # - cil-astra
  # - ccpi-regulariser
  # - tomophantom