on:
  release:
    types: [published]
  push:
    branches: [ main ]
    tags:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: test-gh-actions
        fetch-depth: 0
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
    - name: install 
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential --fix-missing
        conda install ipp -c intel
