name: conda_and_docs_build_and_publish

on:
  release:
    types: [published]
  push:
    branches: [ main ]
    tags:
      - '**'
    paths-ignore:
    - 'recipe/*ba*'
    - '*CHANGELOG.md'
    - '*README.md'
  pull_request:
    branches: [ main ] 
    paths-ignore:
    - '**recipe/*ba*'
    - '**CHANGELOG.md'
    - '**README.md'

    
jobs:
  conda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: paskino/conda-package-publish-action@v1.4.4
      with:
        subDir: 'recipe'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        publish: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
        channels: '-c conda-forge'
        test_all: ${{(github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')) || (github.ref == 'refs/heads/master')}}
    - name: Upload artifact of the conda package.
      uses: actions/upload-artifact@v2
      with:
        name: test-gh-actions-package
        path: recipe/noarch/hello*
  docs_build:
    needs: conda
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: change directory
      run: |
        ls
    - name: Download artifact of the conda package.
      uses: actions/download-artifact@v2
      with:
        name: 'test-gh-actions-package'
        path: 'conda_package'
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.7
        #activate-environment: test-gh-actions-build
    - uses: lauramurgatroyd/build-sphinx-action@v0.0.1
      with:
        DOCS_PATH: 'docs'
        CONDA_BUILD_ENV_FILEPATH: 'docs/docs_environment.yml'
        ARTIFACT_NAME: 'DocumentationHTML'
        PACKAGE_FOLDER_PATH: 'conda_package'
        PACKAGE_NAME: 'hello_world'
        PACKAGE_CONDA_CHANNELS: 'ccpi'
        BUILD_SUBDIR_NAME: 'nightly'
  docs_publish:
    needs: docs_build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - name: Download artifact of the html output.
      uses: actions/download-artifact@v3
      with:
        name: DocumentationHTML
        path: docs/build
    - name: redirect to nightly
      run: >
        sed 's#DESTINATION#https://lauramurgatroyd.github.io/test-gh-actions/nightly/#g' 
        docs/.redirect-template.html
        > docs/build/index.html
    - name: Push changes
      uses: casperdcl/push-dir@v1
      with:
        message: Update documentation
        branch: gh-pages
        dir: docs/build
        nojekyll: true






