name: conda_and_docs_build_and_publish

on:
  release:
    types: [published]
  push:
    branches: [ main ]
    tags:
      - '**'
  pull_request:
    branches: [ main ]
    
jobs:
  conda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: paskino/conda-package-publish-action@add_apt_packages
      with:
        subDir: 'recipe'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        publish: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
        channels: '-c conda-forge'
        test_all: ${{(github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')) || (github.ref == 'refs/heads/master')}}
    - name: Upload artifact of the conda package.
      uses: actions/upload-artifact@v2
      with:
        name: test-gh-actions-package
        path: recipe/noarch/hello*
  docs_build:
    needs: conda
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: change directory
      run: |
        ls
    - name: Download artifact of the conda package.
      uses: actions/download-artifact@v2
      with:
        name: 'test-gh-actions-package'
        path: 'conda_package'
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.7
        #activate-environment: test-gh-actions-build
    - uses: lauramurgatroyd/build-sphinx-action@v0.0.1
      with:
        DOCS_PATH: 'docs'
        CONDA_BUILD_ENV_FILEPATH: 'docs/docs_environment.yml'
        ARTIFACT_NAME: 'DocumentationHTML'
        PACKAGE_FOLDER_PATH: 'conda_package'
        PACKAGE_NAME: 'hello_world'
        PACKAGE_CONDA_CHANNELS: 'ccpi'
        BUILD_SUBDIR_NAME: 'nightly'
  docs_publish:
    needs: docs_build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Download artifact of the html output.
      uses: actions/download-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/build
    - name: Commit documentation changes
      run: |
        git clone https://github.com/lauramurgatroyd/test-gh-actions.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}


