on:
  release:
    types: [published]
  push:
    branches: [ main ]
    tags:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: test-gh-actions
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - name: install conda
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda list
        cd test-gh-actions
        $CONDA/bin/conda install conda-build -c anaconda
        $CONDA/bin/conda build recipe -c conda-forge
        $CONDA/bin/conda install hello_world -c local
        $CONDA/bin/conda list
    - name: test conda
      run: |
          $CONDA/bin/conda list
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "test-gh-actions/docs/"
        build-command: sphinx-build source build/nightly
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: test-gh-actions/docs/build/
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Download artifact of the html output.
      uses: actions/download-artifact@v2
      with:
        name: DocumentationHTML
        path: test-gh-actions/docs/build/
    - name: Commit documentation changes
      run: |
        git clone https://github.com/lauramurgatroyd/test-gh-actions.git --branch gh-pages --single-branch gh-pages
        cp -r test-gh-actions/docs/build/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
