name: create_redirect_file

on:
  release:
    types: [published]
  push:
    branches: [ main ]
    tags:
      - '**'
    paths-ignore:
    - 'recipe/*ba*'
    - '*CHANGELOG.md'
    - '*README.md'
  pull_request:
    branches: [ main ] 
    paths-ignore:
    - '**recipe/*ba*'
    - '**CHANGELOG.md'
    - '**README.md'

    
jobs:
  redirect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: redirect to nightly
      run: >
        sed 's#DESTINATION#https://lauramurgatroyd.github.io/test-gh-actions/nightly/#g' 
        docs/.redirect-template.html
        > docs/index.html
    - name: print
      run: cat docs/index.html
        
